### ISSUE TITLE
lean18.06 x86云编译lucky编译失败

### ISSUE THREAD

**Issue by firkerword** [sirpdboy/luci-app-lucky#1]
/workdir/openwrt/tmp/.lucky_1.5.1_Linux_x86_64.tar.gz.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "lucky_1.5.1_Linux_x86_64.tar.gz" "skip" "" "https://github.com/gdy666/lucky/releases/download/v1.5.1/"    '
rm -rf /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky.installed /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky
mkdir -p /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky
install -d -m0755 /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/usr/bin /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/etc/init.d /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/etc/uci-defaults /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/etc/lucky
install -m0755 /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/lucky /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/usr/bin/lucky
install: cannot stat '/workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/lucky': No such file or directory
make[3]: *** [Makefile:65: /workdir/openwrt/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky.installed] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/lucky/lucky'
time: package/lucky/lucky/compile#0.20#0.05#0.24
    ERROR: package/lucky/lucky failed to build.
make[2]: *** [package/Makefile:116: package/lucky/lucky/compile] Error 1

**Comment by sirpdboy** [comment]
更新了一下。试试。。
