### ISSUE TITLE
大佬，能否将LUCKY的登录改为设置的后面？见图！

### ISSUE THREAD

**Issue by zxlhhyccc** [sirpdboy/luci-app-lucky#15]
![image](https://user-images.githubusercontent.com/45259624/203697682-f3302f2c-0b06-4682-9e13-3d8be8663e11.png)

**Comment by sirpdboy** [comment]
可以改。 设置放前面？ 这意思 吗？

**Comment by zxlhhyccc** [comment]
> 可以改。 设置放前面？ 这意思 吗？

是的啊，如果放左边很不方便，麻烦将设置放前面，客户端放在设置的后面就顺手多了。。。
我改了一下，可是我改不了。。。

**Comment by sirpdboy** [comment]
改了一下，链接也生效了。应该没问题了。
