### ISSUE TITLE
lean X86-64源码编译lucky核心插件失败

### ISSUE THREAD

**Issue by firkerword** [sirpdboy/luci-app-lucky#19]
编译时间:12-29 6时
源码版本:实时拉取最新源码
架构型号:X86-64
错误日志:
make[3]: Entering directory '/workdir/openwrt/package/lucky/lucky'
Makefile:92: *** missing separator.  Stop.
make[3]: Leaving directory '/workdir/openwrt/package/lucky/lucky'
time: package/lucky/lucky/compile#0.11#0.02#0.13
    ERROR: package/lucky/lucky failed to build.
make[2]: *** [package/Makefile:116: package/lucky/lucky/compile] Error 1
make[2]: Leaving directory

**Comment by zxlhhyccc** [comment]
> 编译时间:12-29 6时 源码版本:实时拉取最新源码 架构型号:X86-64 错误日志: make[3]: Entering directory '/workdir/openwrt/package/lucky/lucky' Makefile:92: *** missing separator. Stop. make[3]: Leaving directory '/workdir/openwrt/package/lucky/lucky' time: package/lucky/lucky/compile#0.11#0.02#0.13 ERROR: package/lucky/lucky failed to build. make[2]: *** [package/Makefile:116: package/lucky/lucky/compile] Error 1 make[2]: Leaving directory

请将错误日志贴多一些！

**Comment by firkerword** [comment]
> 
感谢回复！
我用的GitHub云编译，上个版本编译正常，今早报错项目被删了，看了好半天相关日志就这么一点，指向92行，也没看出具体哪的问题🥲

**Comment by firkerword** [comment]
> 



> > 编译时间:12-29 6时 源码版本:实时拉取最新源码 架构型号:X86-64 错误日志: make[3]: Entering directory '/workdir/openwrt/package/lucky/lucky' Makefile:92: *** missing separator. Stop. make[3]: Leaving directory '/workdir/openwrt/package/lucky/lucky' time: package/lucky/lucky/compile#0.11#0.02#0.13 ERROR: package/lucky/lucky failed to build. make[2]: *** [package/Makefile:116: package/lucky/lucky/compile] Error 1 make[2]: Leaving directory
> 
> 请将错误日志贴多一些！

还是报错[日志](https://pipelines.actions.githubusercontent.com/serviceHosts/1d688c8e-b243-4471-bb9a-738b6d0c4e14/_apis/pipelines/1/runs/695/signedlogcontent/2?urlExpires=2022-12-29T14%3A23%3A28.6484892Z&urlSigningMethod=HMACV1&urlSignature=6ZyaN%2FfhlwCmVmhPlfeGHQdOCiBQZnLDKWdico6S9NM%3D)

**Comment by JAM2199562** [comment]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/10511667/210050714-d9fc088e-2ea3-4823-8300-682f2622f94c.png">
@firkerword @zxlhhyccc 我觉得我找到原因了，14号之后的提交变成了CRLF
