### ISSUE TITLE
Lean编译报错，内核选用了6.0.5版本

### ISSUE THREAD

**Issue by 596142041** [sirpdboy/luci-app-lucky#2]
rm -f /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.built
touch /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.built_check
touch /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.built
rm -rf /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky.installed /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky
mkdir -p /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky
install -d -m0755 /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/usr/bin /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/etc/init.d /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/etc/uci-defaults /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky/etc/lucky
install -m0755 /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/lucky /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky
install: cannot stat '/home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/lucky': No such file or directory
make[3]: *** [Makefile:65: /home/lpr/lede/build_dir/target-x86_64_musl/lucky_1.5.1/.pkgdir/lucky.installed] Error 1
make[3]: Leaving directory '/home/lpr/lede/feeds/lucky/lucky'
time: package/feeds/lucky/lucky/compile#0.17#0.06#0.23
    ERROR: package/feeds/lucky/lucky failed to build.
make[2]: *** [package/Makefile:116: package/feeds/lucky/lucky/compile] Error 1

**Comment by sirpdboy** [comment]
更新了一下。试试。。
