### ISSUE TITLE
lucky编译错误

### ISSUE THREAD

**Issue by sherlsenlinmu** [sirpdboy/luci-app-lucky#3]
+ curl -f --connect-timeout 20 --retry 5 --location **https://github.com/gdy666/lucky/releases/download/v1.5.1/lucky_1.5.1_Linux_aarch64.tar.gz**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Download failed.

正确地址：**https://github.com/gdy666/lucky/releases/download/v1.5.1/lucky_1.5.1_Linux_arm64.tar.gz**

**Comment by sherlsenlinmu** [comment]
> 更新了一下。试试。。

ifeq ($(ARCH),aarch64)
	LUCKY_DIR:=armv7

aarch64对应的是arm64吧
问题在于拉取命令与lucky作者打包文件后缀名的框架名不一样

**Comment by sirpdboy** [comment]
发现更新代码有点问题。。代码问题已经修正了。重新编译 的哦
