### ISSUE TITLE
大佬，为什么go方式直接源码编译出现缺少链接库？

### ISSUE THREAD

**Issue by zxlhhyccc** [sirpdboy/luci-app-lucky#7]
![image](https://user-images.githubusercontent.com/45259624/201840732-986a6a3c-3d62-425a-ada2-2f8923c66fa4.png)

**Comment by sirpdboy** [comment]
源码还是 老的版本，。只有编译好的文件 。。。

**Comment by gdy666** [comment]
> > > > 源码还是 老的版本，。只有编译好的文件 。。。
> > > 
> > > 
> > > 大佬，请问哪里有新版本啊？
> > 
> > 
> > 源码会比编译好版本迟几个版本放出,主要看心情o(╯□╰)o,还是建议直接用编译好版本.
> 
> 大佬，一般是版本稳定才会放出源码吧？

不，考虑到的因素很多，lucky一开始的定位是自用小工具，主要是要自己用得爽，没时间精力处理各种奇怪PR审核PR代码安全有没挂马之类的，也不太想闭源，所以源码和二进制程序不同步发布是最省心的。如果开发者真的给程序留后门做手脚，即使是开源的也根本很难防住，何况行也不敢刑啊( ╯□╰ )，如果单纯学习代码目的用旧版本就足够了，暂时也找不到其他人一定要从最新源码编译出最新版本的必要性。

**Comment by zxlhhyccc** [comment]
> > > > > 源码还是 老的版本，。只有编译好的文件 。。。
> > > > 
> > > > 
> > > > 大佬，请问哪里有新版本啊？
> > > 
> > > 
> > > 源码会比编译好版本迟几个版本放出,主要看心情o(╯□╰)o,还是建议直接用编译好版本.
> > 
> > 
> > 大佬，一般是版本稳定才会放出源码吧？
> 
> 不，考虑到的因素很多，lucky一开始的定位是自用小工具，主要是要自己用得爽，没时间精力处理各种奇怪PR审核PR代码安全有没挂马之类的，也不太想闭源，所以源码和二进制程序不同步发布是最省心的。如果开发者真的给程序留后门做手脚，即使是开源的也根本很难防住，何况行也不敢刑啊( ╯□╰ )，如果单纯学习代码目的用旧版本就足够了，暂时也找不到其他人一定要从最新源码编译出最新版本的必要性。

关键是我用旧源码编译缺少链接库，所以我不知道怎么处理，因此我才想用新源码试试！

**Comment by gdy666** [comment]
> > > > > > 源码还是 老的版本，。只有编译好的文件 。。。
> > > > > 
> > > > > 
> > > > > 大佬，请问哪里有新版本啊？
> > > > 
> > > > 
> > > > 源码会比编译好版本迟几个版本放出,主要看心情o(╯□╰)o,还是建议直接用编译好版本.
> > > 
> > > 
> > > 大佬，一般是版本稳定才会放出源码吧？
> > 
> > 
> > 不，考虑到的因素很多，lucky一开始的定位是自用小工具，主要是要自己用得爽，没时间精力处理各种奇怪PR审核PR代码安全有没挂马之类的，也不太想闭源，所以源码和二进制程序不同步发布是最省心的。如果开发者真的给程序留后门做手脚，即使是开源的也根本很难防住，何况行也不敢刑啊( ╯□╰ )，如果单纯学习代码目的用旧版本就足够了，暂时也找不到其他人一定要从最新源码编译出最新版本的必要性。
> 
> 关键是我用旧源码编译缺少链接库，所以我不知道怎么处理，因此我才想用新源码试试！

我在https://github.com/gdy666/lucky/issues/27 不是回复了你，并且给了可以编译的makefile你么？是你自己写的makefile有问题。。。
