### ISSUE TITLE
配置文件保存

### ISSUE THREAD

**Issue by 596142041** [sirpdboy/luci-app-lucky#8]
能否实现将配置文件进行保存，不然每次更新之后配置都需要从新配置

**Comment by gdy666** [comment]
路过，为了防止各种突发情况导致丢失配置，你可以在设置页面下载配置备份，必要时恢复配置就行了。

**Comment by gdy666** [comment]
> 能否实现将配置文件进行保存，不然每次更新之后配置都需要从新配置

最新的[luci-app-lucky](https://github.com/sirpdboy/luci-app-lucky) 我移除了多余的默认配置文件，你看看是否解决了通过IPK包升级更新lucky的时候丢失配置文件的问题。
